pkg/prometheus: add SendExemplars in RemoteWrite
prometheus-operator/prometheus-operator pull request #4160
Opened 2021-07-09 16:00 UTC by coryrjohnson

Adds send_exemplars field to the remote_write configuration in Prometheus

2021-07-12 11:28 UTC, metalmatze requested changes
The code seems correct in terms of the semver however the comment is probably a copy-paste-mistake. Otherwise LGTM :+1:

2021-07-12 11:28 UTC, metalmatze commented on pkg/apis/monitoring/v1/types.go
> +	// Only valid in Prometheus versions 2.15.0 and newer.
```suggestion
	// Only valid in Prometheus versions 2.27.0 and newer.
```

2021-07-12 11:28 UTC, metalmatze commented on example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
> +                      description: Only valid in Prometheus versions 2.15.0 and newer.
```suggestion
                      description: Only valid in Prometheus versions 2.27.0 and newer.
```

2021-07-12 11:28 UTC, metalmatze commented on bundle.yaml
> +                      description: Only valid in Prometheus versions 2.15.0 and newer.
```suggestion
                      description: Only valid in Prometheus versions 2.27.0 and newer.
```

2021-07-12 13:17 UTC, coryrjohnson commented
> The code seems correct in terms of the semver however the comment is probably a copy-paste-mistake. Otherwise LGTM 👍

Thanks, updated.

2021-07-13 15:56 UTC, simonpasquier commented on Documentation/api.md
> +| sendExemplars | Enables sending of exemplars over remote write. Note that exemplar storage itself must be enabled for exemplars to be scraped in the first place.  Only valid in Prometheus versions
This file is generated from `pkg/apis/monitoring/v1/types.go` so the comment needs to go there.

2021-07-13 15:58 UTC, simonpasquier commented on Documentation/api.md
> +| sendExemplars | Enables sending of exemplars over remote write. Note that exemplar storage itself must be enabled for exemplars to be scraped in the first place.  Only valid in Prometheus versions
Maybe also reference the `enableFeatures` field.

2021-07-13 17:48 UTC, coryrjohnson commented
Let me know how that looks @simonpasquier

2021-07-16 10:02 UTC, simonpasquier reviewed
lgtm

2021-07-16 10:08 UTC, simonpasquier commented on pkg/apis/monitoring/v1/types.go
> +	SendExemplars bool `json:"sendExemplars,omitempty"`
Can you make it *bool? This way, a nil value would stick to whatever default value is chosen by Prometheus.

```suggestion
	SendExemplars *bool `json:"sendExemplars,omitempty"`
```

2021-07-16 13:24 UTC, simonpasquier commented on pkg/prometheus/promcfg.go
> +		if spec.SendExemplars && version.GTE(semver.MustParse("2.27.0")) {
```suggestion
		if spec.SendExemplars != nil && version.GTE(semver.MustParse("2.27.0")) {
```

2021-07-19 13:16 UTC, paulfantom approved these changes
lgtm

2021-07-22 15:20 UTC, simonpasquier approved these changes

2021-07-22 15:46 UTC, simonpasquier commented
@coryrjohnson can you run `make generate` and commit the changes?

2021-08-11 08:11 UTC, mvkrishna86 commented
@coryrjohnson, Thanks for the changes. Eagerly waiting for this to be merged to master.

2021-08-16 13:33 UTC, closed without merging