Prometheus hostnetwork: specify listen address on pod ip
prometheus-operator/prometheus-operator pull request #5134
Opened 2022-11-04 09:47 UTC by lwangrabbit

## Description

when prometheus.spec.hostNetwork=true, it will listen on all ips of the node, which is not security.

To reduce the problem, just specify it only listen on the pod ip.

## Type of change

_What type of changes does your code introduce to the Prometheus operator? Put an `x` in the box that apply._

- [ ] `CHANGE` (fix or feature that would cause existing functionality to not work as expected)
- [ ] `FEATURE` (non-breaking change which adds functionality)
- [ ] `BUGFIX` (non-breaking change which fixes an issue)
- [x] `ENHANCEMENT` (non-breaking change which improves existing functionality)
- [ ] `NONE` (if none of the other choices apply. Example, tooling, build system, CI, docs, etc.)

## Changelog entry

```
prometheus hostnetwork: specify listen address on pod ip
```

2022-11-09 07:15 UTC, simonpasquier commented
lgtm. I'd like to get additional input from @Rajpratik71 and @adamsb6 as I don't have concrete experience using host network.

2022-11-09 08:33 UTC, Rajpratik71 commented
HI @lwangrabbit  @simonpasquier ,

for security reasons advertising Prometheus on Pod IP is a good scenario but it will break and cause issues in other scenarios like:

-  In the cloud where generally we have private IP on the interface while a floating Public IP

- In environments with multiple networks and interfaces

there can be more.

By default enabling this will cause the issue, this can be done optionally through parameters.

2022-11-09 11:00 UTC, lwangrabbit commented
In our scenario, each node has internal ip and external ip，hostNetwork default make pod listen [::]:9090, both internal ip and external ip, but we only want it listen on internal ip. 

May be we can enable it through parameters.

2022-11-09 11:13 UTC, Rajpratik71 commented
> In our scenario, each node has internal ip and external ip，hostNetwork default make pod listen [::]:9090, both internal ip and external ip, but we only want it listen on internal ip.
> 
> May be we can enable it through parameters.

I.e. why same I mentioned, for your use case it is fine to block access but for others, it will create an issue

2022-11-10 23:29 UTC, adamsb6 commented
For our use case this is a non-issue, we don't attach a public IP to the instances we run Prometheus on.

However, I think this code will break us. We need to serve on multiple private IPs.

Additionally, I think this code may be grabbing the desired IP on accident. `podIP` is set in [pkg/kubelet/kuberuntime/kuberuntime_manager.go](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kuberuntime/kuberuntime_manager.go#L822), it's just the first item in the `podIPs` array.

This maps to the the `Network.Ip`attribute yielded by the CRI's `PodSandBoxStatus()`function. As far as I can tell there's no rule for container runtimes on which IP gets the privilege of being *the* IP, so it's up to containerd/Docker/etc. and the behavior could differ. I haven't looked at the runtime code for containerd, but it's possible this could just be the first element of a sorted list, with link-locals filtered out.

To achieve your goal I think you'll need some way to indicate exactly which IP you prefer, and a flag so that we don't alter the current default behavior.

2022-11-10 23:31 UTC, adamsb6 requested changes
I think this would break my use case, I need to serve on all available IPs. Can you make this behavior optional?

See also my comments on the origin of `POD_IP`.

2022-11-11 01:59 UTC, lwangrabbit commented
> I think this would break my use case, I need to serve on all available IPs. Can you make this behavior optional?
> 
> See also my comments on the origin of `POD_IP`.


Thanks！The POD_IP is import which I haven't noticed, which should be fixed on the network you wanted.

2022-11-15 15:36 UTC, simonpasquier commented
Thanks for chiming in! I agree that it needs to be configurable and we want to keep the current behavior (e.g. listen on all interfaces) as the default.

2023-01-16 10:34 UTC, closed without merging