Prepare 0.72 release
prometheus-operator/prometheus-operator pull request #6329
Opened 2024-02-23 19:53 UTC by ArthurSens

2024-02-24 11:23 UTC, dongjiang1989 approved these changes
🎉LGTM

2024-02-24 11:49 UTC, philipgough approved these changes
lgtm

2024-02-26 06:18 UTC, slashpai commented
want to get in https://github.com/prometheus-operator/prometheus-operator/pull/6333 also if possible :)

2024-02-26 15:01 UTC, simonpasquier commented on CHANGELOG.md
> +ScrapeClasses is an experimental feature that allows declaring multiple scrape configurations in the Prometheus/PrometheusAgent CRs that can be consumed by selected scrape-related resources, like Scr
I'd use `objects` or `resources` instead of `CRs`.

2024-02-26 15:03 UTC, simonpasquier reviewed
just a few nits.

2024-02-26 15:03 UTC, simonpasquier commented on CHANGELOG.md
> +* [FEATURE] Adds `ScrapeClasses` to Prometheus, PrometheusAgent, ScrapeConfig, ServiceMonitor, PodMonitor and Probe CRDs. #6199
```suggestion
* [FEATURE] Add `ScrapeClasses` to Prometheus, PrometheusAgent, ScrapeConfig, ServiceMonitor, PodMonitor and Probe CRDs. #6199
```

2024-02-26 15:03 UTC, simonpasquier commented on CHANGELOG.md
> +* [FEATURE] Add support for NS records in the DNS service discovery in the ScrapeConfig CRD. #6235
(nit)
```suggestion
* [FEATURE] Add support for NS records to the DNS service discovery in the ScrapeConfig CRD. #6235
```

2024-02-26 15:03 UTC, simonpasquier commented on CHANGELOG.md
> +* [BUGFIX] Fixed failure of metadata informers when processing deleted objects. #6298
```suggestion
* [BUGFIX] Fix failure of metadata informers when processing deleted objects. #6298
```

2024-02-26 18:32 UTC, ArthurSens commented on CHANGELOG.md
> +ScrapeClasses is an experimental feature that allows declaring multiple scrape configurations in the Prometheus/PrometheusAgent CRs that can be consumed by selected scrape-related resources, like Scr
we declare on the custom resource, not in its definition 🤔 

Agreed that using CR can be confusing though, I'll change to something else

2024-02-27 07:08 UTC, slashpai commented
https://github.com/prometheus-operator/prometheus-operator/pull/6333 is good for review now, if its ok to go in this release :)

2024-02-27 14:04 UTC, simonpasquier commented
@ArthurSens fyi I've found a regression in #6199 which would need fixing before the release.

2024-02-27 19:01 UTC, ArthurSens commented
> @ArthurSens fyi I've found a regression in #6199 which would need fixing before the release: https://github.com/prometheus-operator/prometheus-operator/pull/6199/files#r1504284344

Nice find, thanks for flagging it. I'll try to open a PR tomorrow
 
cc @nicolastakashi in case you can beat me to it :)

2024-03-02 13:11 UTC, onedr0p requested changes
It would be nice if this release also contained the update to the alertmanagerconfigs resource. A new field was added to the pushover_configs called `ttl`

Refs:
- https://github.com/prometheus/alertmanager/pull/3474
- https://prometheus.io/docs/alerting/latest/configuration/#pushover_config

2024-03-02 14:43 UTC, buroa requested changes
Would love to have the new TTL option in this release like @onedr0p said.

2024-03-02 19:24 UTC, ArthurSens commented
> It would be nice if this release also contained the update to the alertmanagerconfigs resource. A new field was added to the pushover_configs called `ttl`
> 
> Refs:
> 
> * [Add missing ttl in pushhover prometheus/alertmanager#3474](https://github.com/prometheus/alertmanager/pull/3474)
> * https://prometheus.io/docs/alerting/latest/configuration/#pushover_config
> 
> Let me know if this is out of scope for this release and I'll open a separate issue instead.

First, we would need someone to implement this feature here in prometheus-operator. Since we don't have any PRs open implementing it, we can't add it to this release

2024-03-04 17:40 UTC, merged