feat(xds): Add support nomad service discovery to the ScrapeConfig CRD
prometheus-operator/prometheus-operator pull request #6485
Opened 2024-04-07 14:06 UTC by dongjiang1989

## Description

_Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request.
If it fixes a bug or resolves a feature request, be sure to link to that issue._

Add support nomad service discovery to the ScrapeConfig CRD

## Type of change

_What type of changes does your code introduce to the Prometheus operator? Put an `x` in the box that apply._

- [ ] `CHANGE` (fix or feature that would cause existing functionality to not work as expected)
- [x] `FEATURE` (non-breaking change which adds functionality)
- [ ] `BUGFIX` (non-breaking change which fixes an issue)
- [ ] `ENHANCEMENT` (non-breaking change which improves existing functionality)
- [ ] `NONE` (if none of the other choices apply. Example, tooling, build system, CI, docs, etc.)

## Verification

Please check the [Prometheus-Operator testing guidelines](../TESTING.md) for recommendations about automated tests.

## Changelog entry

_Please put a one-line changelog entry below. This will be copied to the changelog file during the release process._

```release-note
feat(xds): Add support nomad service discovery to the ScrapeConfig CRD
```

2024-04-07 14:09 UTC, dongjiang1989 commented
@slashpai  PTAL

2024-04-11 11:56 UTC, nicolastakashi commented
Thanks for handling that @dongjiang1989, LGTM 🥳 
I'm going to approve but waiting for the last review from @slashpai since she's more aware of other implementations.

2024-04-11 11:56 UTC, nicolastakashi submitted a review, later dismissed

2024-04-11 14:52 UTC, slashpai requested changes
a few nits

2024-04-11 14:52 UTC, slashpai commented on pkg/apis/monitoring/v1alpha1/scrapeconfig_types.go
> +	// If unset, Prometheus uses its default value.
nit: lets remove this line

2024-04-11 14:52 UTC, slashpai commented on pkg/apis/monitoring/v1alpha1/scrapeconfig_types.go
> +	AllowStale *bool `json:"allowStale"`
nit: missed `omitempty` for optional field

2024-04-11 14:52 UTC, slashpai commented on pkg/apis/monitoring/v1alpha1/scrapeconfig_types.go
> +	Namespace *string `json:"namespace"`
missed `omitempty` for optional field

2024-04-11 14:52 UTC, slashpai commented on pkg/apis/monitoring/v1alpha1/scrapeconfig_types.go
> +	RefreshInterval *v1.Duration `json:"refreshInterval"`
missed `omitempty` for optional field

2024-04-11 14:52 UTC, slashpai commented on pkg/apis/monitoring/v1alpha1/scrapeconfig_types.go
> +	Region *string `json:"region"`
missed `omitempty` for optional field

2024-04-11 14:52 UTC, slashpai commented on pkg/apis/monitoring/v1alpha1/scrapeconfig_types.go
> +	TagSeparator *string `json:"tagSeparator"`
missed `omitempty` for optional field

2024-04-11 14:52 UTC, slashpai commented on pkg/prometheus/resource_selector.go
> +			rejectFn(sc, fmt.Errorf("NomadSDConfigs: %w", err))
```suggestion
			rejectFn(sc, fmt.Errorf("nomadSDConfigs: %w", err))
```

2024-04-11 14:52 UTC, slashpai commented on pkg/prometheus/resource_selector.go
> +func (rs *ResourceSelector) validateNomadSDConfigs(ctx context.Context, sc *monitoringv1alpha1.ScrapeConfig) error {
nit: move after `validateHetznerSDConfigs` just to keep the order of added SD's

2024-04-11 14:52 UTC, slashpai commented on pkg/prometheus/resource_selector_test.go
> +		{
nit: move to end just to keep the order of added tests and SD's

2024-04-12 06:14 UTC, dongjiang1989 commented
> a few nits

Thanks. Fixed.

2024-04-23 11:42 UTC, slashpai approved these changes

2024-04-23 11:44 UTC, merged

2024-04-23 11:51 UTC, slashpai commented
@dongjiang1989 I have the merged the changes as CI didn't report any issues but looks like its complaining in generate action now https://github.com/prometheus-operator/prometheus-operator/actions/runs/8799810147/job/24149623425

can you do a follow-up PR?

2024-04-23 12:54 UTC, dongjiang1989 commented
> @dongjiang1989 I have the merged the changes as CI didn't report any issues but looks like its complaining in generate action now https://github.com/prometheus-operator/prometheus-operator/actions/runs/8799810147/job/24149623425
> 
> can you do a follow-up PR?

Thanks. 👌 I'll add a follow-up PR