[feat] - Refactor KumaSDConfigs
prometheus-operator/prometheus-operator pull request #7241
Opened 2024-12-25 19:54 UTC by Dharma-09

## Description

This pull request refactors the validation logic for the KumaSDConfig struct in the Prometheus Operator. The changes include improving the handling of configuration fields such as `server`, `ClientID`, `TLSConfig` , `ProxyURL`,`AllowRedirect`.

## Fixes
#7203 

## Type of change

_What type of changes does your code introduce to the Prometheus operator? Put an `x` in the box that apply._

- [X] `CHANGE` (fix or feature that would cause existing functionality to not work as expected)
- [ ] `FEATURE` (non-breaking change which adds functionality)
- [ ] `BUGFIX` (non-breaking change which fixes an issue)
- [ ] `ENHANCEMENT` (non-breaking change which improves existing functionality)
- [ ] `NONE` (if none of the other choices apply. Example, tooling, build system, CI, docs, etc.)

## Verification

Please check the [Prometheus-Operator testing guidelines](../TESTING.md) for recommendations about automated tests.

## Changelog entry

_Please put a one-line changelog entry below. This will be copied to the changelog file during the release process._

```release-note
NONE
```

2024-12-27 15:19 UTC, heliapb commented
Hi @Dharma-09 , you need to run  `make --always-make format generate` in order to update the bundle/docs, and so on

2024-12-27 15:26 UTC, heliapb commented on test/e2e/scrapeconfig_test.go
> +								Key: "ca-cert",
Also the pipeline issues seems to be related to indentation, so `"ca-cert"` needs to be at the same level of `v1.LocalObjectReference{Name: "kuma-tls-secret"},`, please check:
https://github.com/prometheus-operator/prometheus-operator/actions/runs/12506100526/job/34890510497?pr=7241

2024-12-29 09:22 UTC, mviswanathsai requested changes
A few comments regarding the e2e tests and version checks.

2024-12-29 09:22 UTC, mviswanathsai commented on test/e2e/scrapeconfig_test.go
> +	},
I would like to see test cases where, 
1. `Server` is not specified at all
2. `Server` value is right. i.e, a string of length >1. (similar to what you have with the "required fields" test case.)

2024-12-29 09:22 UTC, mviswanathsai commented on test/e2e/scrapeconfig_test.go
> +	},
Similarly, I would like to see test cases where,

1. `ClientID` is not specified at all
2. `ClientID` value is right i.e, a string of length >1. (similar to what you have with the "required fields" test case.)

2024-12-29 09:22 UTC, mviswanathsai commented on test/e2e/scrapeconfig_test.go
> +var KumaSDTestCases = []scrapeCRDTestCase{
This means you would need to focus more on the test cases concerning `Server` and `ClientID` fields.

2024-12-29 09:22 UTC, mviswanathsai commented on pkg/apis/monitoring/v1alpha1/scrapeconfig_types.go
>  	// +required
```suggestion
	// +kubebuilder:validation:Pattern:="^http(s)?://.+$"
	// +required
```
AFAIK, the server should only support these two schemas. 
CC: @simonpasquier

2024-12-29 09:22 UTC, mviswanathsai commented on test/e2e/scrapeconfig_test.go
> +	},
For example,
```Go
name: "Server URL Unspecified",
scrapeConfigSpec: monitoringv1alpha1.ScrapeConfigSpec{
			KumaSDConfigs: []monitoringv1alpha1.KumaSDConfig{
				{},
          }
},
expectedError: true,
```

2024-12-29 09:22 UTC, mviswanathsai commented on test/e2e/scrapeconfig_test.go
> +	},
After adding the `Pattern` validation,
```Go
name: "Server URL with HTTPS schema",
scrapeConfigSpec: monitoringv1alpha1.ScrapeConfigSpec{
			KumaSDConfigs: []monitoringv1alpha1.KumaSDConfig{
				{ 
                                 Server: "https://example.com", 
                                 },
          }
},
expectedError: false,
```

2024-12-29 09:22 UTC, mviswanathsai commented on test/e2e/scrapeconfig_test.go
> +	},
```Golang
name: "Server URL with HTTP schema",
scrapeConfigSpec: monitoringv1alpha1.ScrapeConfigSpec{
			KumaSDConfigs: []monitoringv1alpha1.KumaSDConfig{
				{ 
                                 Server: "http://example.com", 
                                 },
          }
},
expectedError: false,
```

2025-01-02 10:43 UTC, mviswanathsai commented on test/e2e/scrapeconfig_test.go
> +					Server: "a",
```suggestion
					Server: "",
```
A string of length 1 is valid.

2025-01-02 10:43 UTC, mviswanathsai commented on test/e2e/scrapeconfig_test.go
> +		name: "Valid KumaSDConfig - Required Fields",
(nit) We can remove this test case.

2025-01-02 10:43 UTC, mviswanathsai commented on test/e2e/scrapeconfig_test.go
> +		name: "Invalid KumaSDConfig - Invalid RefreshInterval Format",
(nit) this could also be removed.

2025-01-02 10:43 UTC, mviswanathsai commented on test/e2e/scrapeconfig_test.go
> +		name: "Invalid KumaSDConfig - Invalid RefreshInterval Format",
(nit)
```suggestion
		name: "Invalid RefreshInterval Format",
```

2025-01-02 10:43 UTC, mviswanathsai commented on pkg/apis/monitoring/v1alpha1/scrapeconfig_types.go
> +	// kubebuilder:validation:Pattern:="^http(s)?://.+$"
```suggestion
	// +kubebuilder:validation:Pattern:="^http(s)?://.+$"
```

2025-01-02 10:43 UTC, mviswanathsai commented on pkg/apis/monitoring/v1alpha1/scrapeconfig_types.go
> +	// kubebuilder:validation:Pattern:="^http(s)?://.+$"
Also, you would need to run `make generate` after this change.

2025-01-29 12:00 UTC, mviswanathsai approved these changes

2025-01-29 12:01 UTC, mviswanathsai commented
(nit) could you also add a few tests for the `v1.Duration` fields?
LGTM otherwise.

CC: @slashpai

2025-02-04 18:16 UTC, slashpai commented on test/e2e/scrapeconfig_test.go
> +	},
Add a case for invalid url also?

2025-03-02 00:16 UTC, Dharma-09 commented
Hi @mviswanathsai I rebased my branch for [PR #7241](https://github.com/prometheus-operator/prometheus-operator/pull/7241), but it pulled in some unintended changes. How can I fix this and keep only my intended updates?
Thank you.

2025-03-02 10:51 UTC, slashpai commented
@Dharma-09 Rebase can be hard sometimes if branch is a bit behind upstream as more changes would have merged.

What I follow to rebase usually is `git pull upstream main --rebase` and follow with fixing if any conflicts. By default if nothing specified `git pull` will be using `merge` strategy to sync your branch which works for some cases. But rebasing is always a better option to have a cleaner git history.

For a easier solution, I would suggest you to create a new branch from current upstream main and cherry-pick your commits from this branch on top of it. 

If you are unsure about any git commands its always better to create a backup of current branch, so incase if something is messed up its easy to fix :)

2025-03-03 20:05 UTC, closed without merging