chore: Refactor OpenStackSDConfig
prometheus-operator/prometheus-operator pull request #7244
Opened 2024-12-28 04:21 UTC by nutmos

## Description

Refactor OpenStackSDConfig

## Type of change

_What type of changes does your code introduce to the Prometheus operator? Put an `x` in the box that apply._

- [ ] `CHANGE` (fix or feature that would cause existing functionality to not work as expected)
- [ ] `FEATURE` (non-breaking change which adds functionality)
- [ ] `BUGFIX` (non-breaking change which fixes an issue)
- [x] `ENHANCEMENT` (non-breaking change which improves existing functionality)
- [ ] `NONE` (if none of the other choices apply. Example, tooling, build system, CI, docs, etc.)

## Verification

Please check the [Prometheus-Operator testing guidelines](../TESTING.md) for recommendations about automated tests.

## Changelog entry

```release-note
1. Add the validation in the type.
```

2024-12-29 08:45 UTC, mviswanathsai commented
Hey! thanks for the contribution. 
On top of this, you would also need to add e2e test cases and version checks wherever applicable. You can ping me if you need any help with that!

2024-12-29 13:08 UTC, nutmos commented
@mviswanathsai Hi, I completed all of the requirements already. Please review.

2025-01-22 01:45 UTC, nutmos commented
@mviswanathsai Hi, do you have any chance to take a look at my PR?

2025-01-28 05:16 UTC, slashpai requested changes
For string fields we need to add the minlength validation
```
// +kubebuilder:validation:MinLength:=1
```

2025-01-29 13:17 UTC, nutmos commented
@slashpai I updated already. Please review

2025-01-30 01:41 UTC, nutmos commented
@mviswanathsai @slashpai Hi, I fixed already. Please review. Thank you!

2025-01-30 05:27 UTC, slashpai commented
Can you add testcases for all the fields updated in API in e2e test file?

2025-01-30 05:34 UTC, slashpai commented on pkg/apis/monitoring/v1alpha1/scrapeconfig_types.go
> +	// +kubebuilder:validation:Pattern:="^http(s)?://.+$"
I am not very good with regex but I tested this in https://regex101.com and it throws error.
Also I think it should `^http(s)?:\/\/.+$`, so adding the testcase in e2e would help to verify this

2025-01-30 10:42 UTC, nutmos commented
@slashpai I updated the pattern as suggested already along with the new test cases to cover field updates.
Also, I would like to highlight that there are other HTTP-related fields use this pattern, which I will help updating them later as well.

2025-01-30 10:57 UTC, mviswanathsai reviewed
Great job with the extensive testcases, just one comment.
CC: @slashpai

2025-01-30 10:57 UTC, mviswanathsai commented on test/e2e/scrapeconfig_test.go
> +var OpenStackSDTestCases = []scrapeCRDTestCase{
Overall looks great. I would like to see a few testcases where `+required` fields are not specified and we expect errors. 
For example, the name of the testcase would be: `name: "Role unspecified"`, `name: "Region unspecified"`

2025-01-30 13:02 UTC, nutmos commented on test/e2e/scrapeconfig_test.go
> +var OpenStackSDTestCases = []scrapeCRDTestCase{
@mviswanathsai Added

2025-01-30 13:05 UTC, nutmos commented
@mviswanathsai I added 2 more cases to cover the missing required fields.

2025-02-01 11:04 UTC, nutmos commented
@mviswanathsai Update the code with rebase from the main branch. Please review.

2025-02-03 06:03 UTC, mviswanathsai commented
LGTM! 
CC: @slashpai

2025-02-04 13:40 UTC, nutmos commented
@slashpai any action needed from my side?

2025-02-04 14:18 UTC, slashpai approved these changes
Thank you, lgtm

2025-02-04 14:21 UTC, merged